package pointofsale;

import java.math.BigDecimal;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;



/**
 *
 * Klasa reprezentująca główne okno aplikacji, na którym wyświetlane są informacje
 * o zeskanowanych produktach jak również ich całkowitej cenie. Wyświetlane informacje
 * są niezależne od działania aplikacji, klasa służy jednynie do wyświetlania danych.
 */
public class POSForm extends javax.swing.JFrame {

    
    /**
     * Creates new form MainWindow
     */
    public POSForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produkt", "ID", "Ilość", "Cena", "Należność"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("zł");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("0");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Total:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public static void main(String args[]) {

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSForm().setVisible(true);
            }
        });        
    }
    
    /**
     * Metoda służąca do dodawania produktu do tabeli
     * @param item produkt do dodania do tabeli
     */
    public void addElementToTable(OrderItem item)
    {      
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();       // pobranie modelu tabeli
        
        Product product = item.getProduct();                
       
        Object[] rowItem = {product.getProductName(),product.getProductID(),item.getQuantity(),product.getProductPrice(),item.getTotal()};    
        model.addRow(rowItem);                                                  // dodaj rząd
    }
    
    /**
     * Metoda służąca do dodania już istniejącego elementu do tabeli. W tym przypadku
     * rząd z danym elementem jest przenoszony na koniec tabeli ze zwiększoną ilością
     * @param item produkt do dodania do tabeli
     */
    public void addExistingElementToTable(OrderItem item)
    {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();       // pobranie modelu tabeli

        for(int i = 0; i < model.getRowCount(); i++)
        {
            if(model.getValueAt(i,1).equals(item.getProduct().getProductID()))  // usuniecie danego rzedu
            {
                model.removeRow(i);
                break;
            }                
        }  
        addElementToTable(item);                                                // dodanie nowego elementu na koniec tabeli
    }
    
    /**
     * Uaktualnienie należności za zakupy
     * @param bd aktualna wartość
     */
    public void setTotal (BigDecimal bd)
    {
        jLabel2.setText(bd.toString());
    }
        
    /**
     * Metoda służąca do wyczyszczenia danych w tabeli i wyzerowania należnosci
     */
    public void reset()
    {
        setTotal(BigDecimal.ZERO);                                              // ustawienie należności na 0
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();       // pobranie modelu tabeli
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
        model.removeRow(i);                                                     // wyczyszczenie tabeli
        }
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
